### PR TITLE
Updated po-files from Crowdin

### PR DESCRIPTION
**Pull request by Hakansv**
Not so much done in Crowdin. But these are have been worked on so far:

image

### CODE REVIEW

**Comment by canne** [comment]
Thanks, Håkan, much appreciated!

Do you want me to make a release out of this, like `v1.5.111` as I announced, as a plan? I could do that but there are some issues for that in CI which I do not have time to resolve while developing already in 2.0; would you be able to do fix those? See above, Appveyor Windows fails at:
```
  C:/project/dashboard_pi/po/el_GR.po:5: warning: header field 'Last-Translator' still has the initial default value
  dashboard_tactics-i18n [es_ES]: Created mo file.
  dashboard_tactics-i18n [et_EE]: Created mo file.
  dashboard_tactics-i18n [fi_FI]: Created mo file.
  C:/project/dashboard_pi/po/fi_FI.po:5: warning: header field 'Last-Translator' still has the initial default value
  dashboard_tactics-i18n [fil_PH]: Created mo file.
  dashboard_tactics-i18n [fr_FR]: Created mo file.
  C:/project/dashboard_pi/po/fr_FR.po:5: warning: header field 'Last-Translator' still has the initial default value
  C:/project/dashboard_pi/po/fr_FR.po:62: number of format specifications in 'msgid' and 'msgstr' does not match
  C:/project/dashboard_pi/po/fr_FR.po:1019: number of format specifications in 'msgid' and 'msgstr' does not match
  /usr/bin/msgfmt: found 2 fatal errors
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\project\dashboard_pi\build\dashboard_tactics-i18n.vcxproj]
```
Travis CI for Linux fails at:
```
Scanning dependencies of target dashboard_tactics-i18n
[  2%] dashboard_tactics-i18n [ar_SA]: Created mo file.
[  2%] dashboard_tactics-i18n [zh_TW]: Created mo file.
[  4%] dashboard_tactics-i18n [ca_ES]: Created mo file.
[  5%] dashboard_tactics-i18n [cs_CZ]: Created mo file.
[  5%] dashboard_tactics-i18n [da_DK]: Created mo file.
[  6%] dashboard_tactics-i18n [de_DE]: Created mo file.
[  8%] dashboard_tactics-i18n [el_GR]: Created mo file.
[  9%] dashboard_tactics-i18n [es_ES]: Created mo file.
[  9%] dashboard_tactics-i18n [et_EE]: Created mo file.
[ 10%] dashboard_tactics-i18n [fi_FI]: Created mo file.
[ 12%] dashboard_tactics-i18n [fil_PH]: Created mo file.
[ 13%] dashboard_tactics-i18n [fr_FR]: Created mo file.
/home/travis/build/canne/dashboard_tactics_pi/po/fr_FR.po:62: number of format specifications in 'msgid' and 'msgstr' does not match
/home/travis/build/canne/dashboard_tactics_pi/po/fr_FR.po:1019: number of format specifications in 'msgid' and 'msgstr' does not match[ 15%] dashboard_tactics-i18n [gl_ES]: Created mo file.
/usr/bin/msgfmt: found 2 fatal errors
make[2]: *** [fr_FR.mo] Error 1
make[2]: *** Deleting file `fr_FR.mo'
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/dashboard_tactics-i18n.dir/all] Error 2
make: *** [all] Error 2
The command "if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_BUILD_TYPE=Release ../ && make -sj2 package; fi" exited with 2.
```
Travis CI for OSX fails at:
```
-- Build files have been written to: /Users/travis/build/canne/dashboard_tactics_pi/build
Scanning dependencies of target dashboard_tactics-i18n
[  1%] dashboard_tactics-i18n [zh_TW]: Created mo file.
[  2%] dashboard_tactics-i18n [ar_SA]: Created mo file.
[  2%] dashboard_tactics-i18n [ca_ES]: Created mo file.
[  4%] dashboard_tactics-i18n [cs_CZ]: Created mo file.
[  5%] dashboard_tactics-i18n [da_DK]: Created mo file.
[  6%] dashboard_tactics-i18n [de_DE]: Created mo file.
[  6%] dashboard_tactics-i18n [el_GR]: Created mo file.
/Users/travis/build/canne/dashboard_tactics_pi/po/el_GR.po:5: warning: header field 'Last-Translator' still has the initial default value
[  8%] dashboard_tactics-i18n [es_ES]: Created mo file.
[  9%] dashboard_tactics-i18n [et_EE]: Created mo file.
[ 11%] dashboard_tactics-i18n [fi_FI]: Created mo file.
/Users/travis/build/canne/dashboard_tactics_pi/po/fi_FI.po:5: warning: header field 'Last-Translator' still has the initial default value
[ 11%] dashboard_tactics-i18n [fil_PH]: Created mo file.
[ 12%] dashboard_tactics-i18n [fr_FR]: Created mo file.
/Users/travis/build/canne/dashboard_tactics_pi/po/fr_FR.po:5: warning: header field 'Last-Translator' still has the initial default value
/Users/travis/build/canne/dashboard_tactics_pi/po/fr_FR.po:62: number of format specifications in 'msgid' and 'msgstr' does not match
/Users/travis/build/canne/dashboard_tactics_pi/po/fr_FR.po:1019: number of format specifications in 'msgid' and 'msgstr' does not match
/usr/local/opt/gettext/bin/msgfmt: found 2 fatal errors
make[2]: *** [fr_FR.mo] Error 1
make[2]: *** Deleting file `fr_FR.mo'
make[2]: *** Waiting for unfinished jobs....
[ 13%] dashboard_tactics-i18n [gl_ES]: Created mo file.
make[1]: *** [CMakeFiles/dashboard_tactics-i18n.dir/all] Error 2
make: *** [all] Error 2
The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DwxWidgets_CONFIG_EXECUTABLE=/tmp/wx312_opencpn50_macos109/bin/wx-config -DwxWidgets_CONFIG_OPTIONS="--prefix=/tmp/wx312_opencpn50_macos109" -DCMAKE_INSTALL_PREFIX=/tmp/opencpn -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 .. && make -sj2 && make create-pkg; fi" exited with 2.
0.02s$ ls -l;
total 880
-rw-r--r--   1 travis  staff   20561 Mar 14 07:03 CMakeCache.txt
drwxr-xr-x  19 travis  staff     646 Mar 14 07:03 CMakeFiles
-rw-r--r--   1 travis  staff    4212 Mar 14 07:03 CPackConfig.cmake
-rw-r--r--   1 travis  staff    4623 Mar 14 07:03 CPackSourceConfig.cmake
-rw-r--r--   1 travis  staff   37659 Mar 14 07:03 DashboardTactics.pkgproj
-rw-r--r--   1 travis  staff   65106 Mar 14 07:03 Makefile
drwxr-xr-x  14 travis  staff     476 Mar 14 07:03 Resources
-rw-r--r--   1 travis  staff    2730 Mar 14 07:03 ar_SA.mo
-rw-r--r--   1 travis  staff    4933 Mar 14 07:03 ca_ES.mo
-rw-r--r--   1 travis  staff   31869 Mar 14 07:03 cmake_install.cmake
-rw-r--r--   1 travis  staff    5483 Mar 14 07:03 cs_CZ.mo
-rw-r--r--   1 travis  staff    5284 Mar 14 07:03 da_DK.mo
-rw-r--r--   1 travis  staff    5460 Mar 14 07:03 de_DE.mo
-rw-r--r--   1 travis  staff   24625 Mar 14 07:03 el_GR.mo
-rw-r--r--   1 travis  staff    5565 Mar 14 07:03 es_ES.mo
-rw-r--r--   1 travis  staff    5470 Mar 14 07:03 et_EE.mo
-rw-r--r--   1 travis  staff   15659 Mar 14 07:03 fi_FI.mo
-rw-r--r--   1 travis  staff     492 Mar 14 07:03 fil_PH.mo
-rw-r--r--   1 travis  staff    3233 Mar 14 07:03 gl_ES.mo
-rw-r--r--   1 travis  staff   21462 Mar 14 07:03 license.txt
-rw-r--r--   1 travis  staff  133246 Mar 14 07:03 pkg_background.jpg
-rw-r--r--   1 travis  staff     498 Mar 14 07:03 zh_TW.mo
```

**Comment by canne** [comment]
Thanks, Håkan, I'll build and publish `v1.5.111` with this.

**Comment by Hakansv** [comment]
Sorry, I should have tested.
The error was from a translator fail to two strings. The user had changed the code part of string like the example below. It's a bit tricky for a translator to understand all parts of such a string. Crowdin use to warn about mismatches like this but it's possible to override. If it's easy to avoid such strings in the code it's preferable.
Now corrected in a new PR.


#: src\wind_history.cpp:847
#, c-format
msgid "Max %.1f %s since %02d:%02d  Overall %.1f %s"
msgstr "Max %.1f depuis  %02d:%02d Absolu %.1f %s"

**Comment by canne** [comment]
No problem, all PR checks passed now. I'm still in a flying fish branch of the 2.0 but once that 'transpiles' (TypeScript!) I'll switch back to 1.5 and push this out. I can run a few simple tests only on  Windows and RPI right now; I am in my boat - but I reckon other Linuxians have no problems and I have never got any feedback from an OSX user, anyway.

Thanks for the great help!

**Pull request merged**
